on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v18
      with:
        globs: '**/*.md'
        config: '.markdownlint.yaml'
        fix: true
    - uses: huacnlee/autocorrect-action@v2